---
# PERSONAL INFORMATION
title: Firstname M. Lastname, PhD
subtitle: Postdoctoral Research Fellow
author: Firstname Lastname
date: '2023-06-05'
location: City, Country
phone: '+44 1234 567 890'  # be careful sharing this online
email: local@domain.com  # be careful sharing this online
website: domain.com

# SUMMARY (example)
# abstract-title: Summary
# abstract: |
#   Here is a summary of my research interests and experience.

# BIBLIOGRAPHY (example; use --citeproc with pandoc to process citations)
# bibliography: citations.bib
# link-citations: true
# reference-section-title: Bibliography

# HTML (defaults commented out)
# html:
  # fontsize: 12pt
  # mainfont: \'Noto Sans\', sans-serif
  # maxwidth: 45em                       # max width of body text
  # fontcolor: '#1a1a1a'
  # backgroundcolor: '#fdfdfd'
  # linkcolor: '#0000ff'
  # margin-left: 50px
  # margin-right: 50px
  # margin-top: 50px
  # margin-bottom: 50px
  # monofont: \'Noto Sans Mono\', monospace
  # monobackgroundcolor:

# LaTeX (defaults commented out)
# latex:
  # fontsize: 10pt
  # fontfamily: noto
  # fontfamilyoptions: sfdefault
  # fontenc: T1
  # babelfonts:
  # papersize: a4
  # classoptions:
  # geometryoptions: 
  #   - margin=3cm
  # pagestyle: fancy
  # secnumdepth: 5                       # depth of numbering if numbering sections
  # linkcolor:
  #   model: named                       # color model, e.g. named, RGB, HTML, etc. (see xcolor package)
  #   spec: Blue                         # color specification, e.g. Blue, '0, 0, 255', 0000ff etc.
  # hidelinks:                           # hide links in the document (no colors or borders)
  # links-as-notes:                      # links in footnotes, doesn't work currently
  # urlstyle:
  # hyperrefoptions:
  # indent:                              # indent paragraphs instead of vertical space
  # block-headings:
  # biblatexoptions:
  # natbiboptions:
  # biblio-style:
  # microtypeoptions:

  # XeTeX/LuaTeX specific (defaults commented out)
  # mainfont:
  # sansfont:
  # monofont:
  # mathfont:
  # mainfontoptions:
  # sansfontoptions:
  # monofontoptions:
  # mathfontoptions:
  # fontfamilies:
  #   - name:
  #     options:
  #     font:
  # CJKmainfont:
  # CJKsansfont:
  # CJKmonofont:
  # CJKoptions:
  # mathspec:
---
